on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - uses: haskell/actions/setup@v1.2.1
        name: Setup
        with:
          enable-stack: true
          stack-version: 2.7.1
          stack-no-global: true

      - uses: actions/cache@v2.1.6
        name: Cache
        with:
          path: ~/.stack
          key: ${{ runner.os }}-stack-${{ hashFiles('stack.yaml', 'stack.yaml.lock') }}-${{ hashFiles('**.cabal') }}
          restore-keys: ${{ runner.os }}-stack-

      - name: Install dependencies
        run: stack build --test --bench --no-run-tests --no-run-benchmarks --only-dependencies

      - name: Collect pedantic warnings
        run: stack build --test --bench --no-run-tests --no-run-benchmarks --ghc-options="-Wall -Wno-missing-signatures -Wno-name-shadowing -Wno-unused-do-bind -Wno-unused-top-binds"

      - name: Build
        run: stack build --test --bench --no-run-tests --no-run-benchmarks --ghc-options="-Werror -Wall -Wno-missing-signatures -Wno-name-shadowing -Wno-unused-do-bind -Wno-unused-top-binds"

      - name: Test
        run: stack test
